// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(reset,0,0);
        VL_OUT8(is_halted,0,0);
        CData/*0:0*/ top__DOT__reset;
        CData/*0:0*/ top__DOT__clk;
        CData/*0:0*/ top__DOT__is_halted;
        CData/*0:0*/ top__DOT__cpu__DOT__reset;
        CData/*0:0*/ top__DOT__cpu__DOT__clk;
        CData/*0:0*/ top__DOT__cpu__DOT__is_halted;
        CData/*0:0*/ top__DOT__cpu__DOT__PCWrite;
        CData/*0:0*/ top__DOT__cpu__DOT__is_hazard;
        CData/*0:0*/ top__DOT__cpu__DOT__IF_ID_inst_write;
        CData/*0:0*/ top__DOT__cpu__DOT__is_hit;
        CData/*0:0*/ top__DOT__cpu__DOT__is_output_valid;
        CData/*0:0*/ top__DOT__cpu__DOT__is_input_valid;
        CData/*0:0*/ top__DOT__cpu__DOT__mem_rw;
        CData/*0:0*/ top__DOT__cpu__DOT__CacheStall;
        CData/*0:0*/ top__DOT__cpu__DOT__is_ecall;
        CData/*0:0*/ top__DOT__cpu__DOT__mem_read;
        CData/*0:0*/ top__DOT__cpu__DOT__mem_to_reg;
        CData/*0:0*/ top__DOT__cpu__DOT__mem_write;
        CData/*0:0*/ top__DOT__cpu__DOT__write_enable;
        CData/*0:0*/ top__DOT__cpu__DOT__pc_to_reg;
        CData/*0:0*/ top__DOT__cpu__DOT__is_jal;
        CData/*0:0*/ top__DOT__cpu__DOT__is_jalr;
        CData/*0:0*/ top__DOT__cpu__DOT__branch;
        CData/*0:0*/ top__DOT__cpu__DOT__actual_taken;
        CData/*0:0*/ top__DOT__cpu__DOT__pred_taken;
        CData/*0:0*/ top__DOT__cpu__DOT__update_B_history;
        CData/*0:0*/ top__DOT__cpu__DOT__update_B_target;
        CData/*1:0*/ top__DOT__cpu__DOT__alu_src_B;
        CData/*1:0*/ top__DOT__cpu__DOT__forwardA;
        CData/*1:0*/ top__DOT__cpu__DOT__forwardB;
        CData/*4:0*/ top__DOT__cpu__DOT__rs1_in;
        CData/*0:0*/ top__DOT__cpu__DOT__alu_bcond;
        CData/*3:0*/ top__DOT__cpu__DOT__alu_op;
        CData/*0:0*/ top__DOT__cpu__DOT__miss;
        CData/*0:0*/ top__DOT__cpu__DOT__IF_ID_miss;
        CData/*0:0*/ top__DOT__cpu__DOT__IF_ID_pred_taken;
        CData/*1:0*/ top__DOT__cpu__DOT__ID_EX_alu_src_B;
        CData/*0:0*/ top__DOT__cpu__DOT__ID_EX_is_jal;
        CData/*0:0*/ top__DOT__cpu__DOT__ID_EX_is_jalr;
        CData/*0:0*/ top__DOT__cpu__DOT__ID_EX_branch;
        CData/*0:0*/ top__DOT__cpu__DOT__ID_EX_mem_write;
        CData/*0:0*/ top__DOT__cpu__DOT__ID_EX_mem_read;
        CData/*0:0*/ top__DOT__cpu__DOT__ID_EX_mem_to_reg;
        CData/*0:0*/ top__DOT__cpu__DOT__ID_EX_reg_write;
        CData/*0:0*/ top__DOT__cpu__DOT__ID_EX_is_halted;
        CData/*0:0*/ top__DOT__cpu__DOT__ID_EX_pc_to_reg;
        CData/*4:0*/ top__DOT__cpu__DOT__ID_EX_rs1;
        CData/*4:0*/ top__DOT__cpu__DOT__ID_EX_rs2;
        CData/*4:0*/ top__DOT__cpu__DOT__ID_EX_rd;
        CData/*0:0*/ top__DOT__cpu__DOT__ID_EX_pred_taken;
        CData/*0:0*/ top__DOT__cpu__DOT__EX_MEM_mem_write;
        CData/*0:0*/ top__DOT__cpu__DOT__EX_MEM_mem_read;
        CData/*0:0*/ top__DOT__cpu__DOT__EX_MEM_is_halted;
        CData/*0:0*/ top__DOT__cpu__DOT__EX_MEM_pc_to_reg;
        CData/*0:0*/ top__DOT__cpu__DOT__EX_MEM_mem_to_reg;
        CData/*0:0*/ top__DOT__cpu__DOT__EX_MEM_reg_write;
        CData/*4:0*/ top__DOT__cpu__DOT__EX_MEM_rd;
        CData/*0:0*/ top__DOT__cpu__DOT__MEM_WB_mem_to_reg;
        CData/*0:0*/ top__DOT__cpu__DOT__MEM_WB_reg_write;
        CData/*0:0*/ top__DOT__cpu__DOT__MEM_WB_is_halted;
        CData/*0:0*/ top__DOT__cpu__DOT__MEM_WB_pc_to_reg;
    };
    struct {
        CData/*4:0*/ top__DOT__cpu__DOT__MEM_WB_rd;
        CData/*0:0*/ top__DOT__cpu__DOT____Vcellinp__pc__PCWrite;
        CData/*0:0*/ top__DOT__cpu__DOT__pc__DOT__reset;
        CData/*0:0*/ top__DOT__cpu__DOT__pc__DOT__clk;
        CData/*0:0*/ top__DOT__cpu__DOT__pc__DOT__PCWrite;
        CData/*0:0*/ top__DOT__cpu__DOT__branch_predictor__DOT__reset;
        CData/*0:0*/ top__DOT__cpu__DOT__branch_predictor__DOT__clk;
        CData/*0:0*/ top__DOT__cpu__DOT__branch_predictor__DOT__update_B_history;
        CData/*0:0*/ top__DOT__cpu__DOT__branch_predictor__DOT__update_B_target;
        CData/*0:0*/ top__DOT__cpu__DOT__branch_predictor__DOT__actual_taken;
        CData/*0:0*/ top__DOT__cpu__DOT__branch_predictor__DOT__pred_taken;
        CData/*4:0*/ top__DOT__cpu__DOT__branch_predictor__DOT__idx;
        CData/*4:0*/ top__DOT__cpu__DOT__branch_predictor__DOT__pht_idx;
        CData/*4:0*/ top__DOT__cpu__DOT__branch_predictor__DOT__ID_EX_idx;
        CData/*4:0*/ top__DOT__cpu__DOT__branch_predictor__DOT__ID_EX_pht_idx;
        CData/*4:0*/ top__DOT__cpu__DOT__branch_predictor__DOT__extended_actual_taken;
        CData/*4:0*/ top__DOT__cpu__DOT__branch_predictor__DOT__BHSR;
        CData/*0:0*/ top__DOT__cpu__DOT__branch_predictor__DOT__pred_taken_mux__DOT__Enable;
        CData/*0:0*/ top__DOT__cpu__DOT__miss_mux__DOT__Enable;
        CData/*0:0*/ top__DOT__cpu__DOT__imem__DOT__reset;
        CData/*0:0*/ top__DOT__cpu__DOT__imem__DOT__clk;
        CData/*4:0*/ top__DOT__cpu__DOT__hazard_detection_unit__DOT__IF_ID_rs1;
        CData/*4:0*/ top__DOT__cpu__DOT__hazard_detection_unit__DOT__IF_ID_rs2;
        CData/*0:0*/ top__DOT__cpu__DOT__hazard_detection_unit__DOT__ID_EX_mem_read;
        CData/*4:0*/ top__DOT__cpu__DOT__hazard_detection_unit__DOT__ID_EX_rd;
        CData/*0:0*/ top__DOT__cpu__DOT__hazard_detection_unit__DOT__is_ecall;
        CData/*0:0*/ top__DOT__cpu__DOT__hazard_detection_unit__DOT__ID_EX_reg_write;
        CData/*0:0*/ top__DOT__cpu__DOT__hazard_detection_unit__DOT__is_hazard;
        CData/*0:0*/ top__DOT__cpu__DOT__hazard_detection_unit__DOT__IF_ID_inst_write;
        CData/*0:0*/ top__DOT__cpu__DOT__hazard_detection_unit__DOT__PCWrite;
        CData/*0:0*/ top__DOT__cpu__DOT__reg_file__DOT__reset;
        CData/*0:0*/ top__DOT__cpu__DOT__reg_file__DOT__clk;
        CData/*4:0*/ top__DOT__cpu__DOT__reg_file__DOT__rs1;
        CData/*4:0*/ top__DOT__cpu__DOT__reg_file__DOT__rs2;
        CData/*4:0*/ top__DOT__cpu__DOT__reg_file__DOT__rd;
        CData/*0:0*/ top__DOT__cpu__DOT__reg_file__DOT__write_enable;
        CData/*6:0*/ top__DOT__cpu__DOT__ctrl_unit__DOT__part_of_inst;
        CData/*0:0*/ top__DOT__cpu__DOT__ctrl_unit__DOT__is_jal;
        CData/*0:0*/ top__DOT__cpu__DOT__ctrl_unit__DOT__is_jalr;
        CData/*0:0*/ top__DOT__cpu__DOT__ctrl_unit__DOT__branch;
        CData/*0:0*/ top__DOT__cpu__DOT__ctrl_unit__DOT__mem_read;
        CData/*0:0*/ top__DOT__cpu__DOT__ctrl_unit__DOT__mem_to_reg;
        CData/*0:0*/ top__DOT__cpu__DOT__ctrl_unit__DOT__mem_write;
        CData/*1:0*/ top__DOT__cpu__DOT__ctrl_unit__DOT__alu_src_B;
        CData/*0:0*/ top__DOT__cpu__DOT__ctrl_unit__DOT__write_enable;
        CData/*0:0*/ top__DOT__cpu__DOT__ctrl_unit__DOT__pc_to_reg;
        CData/*0:0*/ top__DOT__cpu__DOT__ctrl_unit__DOT__is_ecall;
        CData/*6:0*/ top__DOT__cpu__DOT__ctrl_unit__DOT__opcode;
        CData/*6:0*/ top__DOT__cpu__DOT__imm_gen__DOT__opcode;
        CData/*4:0*/ top__DOT__cpu__DOT__forwarding_unit__DOT__ID_EX_rs1;
        CData/*4:0*/ top__DOT__cpu__DOT__forwarding_unit__DOT__ID_EX_rs2;
        CData/*4:0*/ top__DOT__cpu__DOT__forwarding_unit__DOT__EX_MEM_rd;
        CData/*4:0*/ top__DOT__cpu__DOT__forwarding_unit__DOT__MEM_WB_rd;
        CData/*0:0*/ top__DOT__cpu__DOT__forwarding_unit__DOT__EX_MEM_reg_write;
        CData/*0:0*/ top__DOT__cpu__DOT__forwarding_unit__DOT__MEM_WB_reg_write;
        CData/*1:0*/ top__DOT__cpu__DOT__forwarding_unit__DOT__forwardA;
        CData/*1:0*/ top__DOT__cpu__DOT__forwarding_unit__DOT__forwardB;
        CData/*1:0*/ top__DOT__cpu__DOT__forwardA_mux__DOT__control;
        CData/*1:0*/ top__DOT__cpu__DOT__forwardB_mux__DOT__control;
        CData/*0:0*/ top__DOT__cpu__DOT__ALUSrc_A_mux__DOT__Enable;
        CData/*1:0*/ top__DOT__cpu__DOT__ALUSrc_B_mux__DOT__control;
        CData/*3:0*/ top__DOT__cpu__DOT__alu_ctrl_unit__DOT__alu_op;
        CData/*6:0*/ top__DOT__cpu__DOT__alu_ctrl_unit__DOT__opcode;
        CData/*2:0*/ top__DOT__cpu__DOT__alu_ctrl_unit__DOT__funct3;
    };
    struct {
        CData/*6:0*/ top__DOT__cpu__DOT__alu_ctrl_unit__DOT__funct7;
        CData/*0:0*/ top__DOT__cpu__DOT__alu_ctrl_unit__DOT__unused;
        CData/*3:0*/ top__DOT__cpu__DOT__alu__DOT__alu_op;
        CData/*0:0*/ top__DOT__cpu__DOT__alu__DOT__alu_bcond;
        CData/*0:0*/ top__DOT__cpu__DOT__branch_calculator__DOT__alu_bcond;
        CData/*0:0*/ top__DOT__cpu__DOT__branch_calculator__DOT__ID_EX_branch;
        CData/*0:0*/ top__DOT__cpu__DOT__branch_calculator__DOT__ID_EX_is_jal;
        CData/*0:0*/ top__DOT__cpu__DOT__branch_calculator__DOT__ID_EX_is_jalr;
        CData/*0:0*/ top__DOT__cpu__DOT__branch_calculator__DOT__actual_taken;
        CData/*0:0*/ top__DOT__cpu__DOT__branch_calculator__DOT__update_B_history;
        CData/*0:0*/ top__DOT__cpu__DOT__branch_calculator__DOT__update_B_target;
        CData/*0:0*/ top__DOT__cpu__DOT__branch_calculator__DOT__is_jalr_mux__DOT__Enable;
        CData/*0:0*/ top__DOT__cpu__DOT__Miss_Detection_Unit__DOT__actual_taken;
        CData/*0:0*/ top__DOT__cpu__DOT__Miss_Detection_Unit__DOT__ID_EX_pred_taken;
        CData/*0:0*/ top__DOT__cpu__DOT__Miss_Detection_Unit__DOT__miss;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__reset;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__clk;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__is_input_valid;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__mem_rw;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__is_output_valid;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__is_hit;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__is_dmem_ready;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__is_dmem_output_valid;
        CData/*3:0*/ top__DOT__cpu__DOT__cache__DOT__clog2;
        CData/*2:0*/ top__DOT__cpu__DOT__cache__DOT__idx;
        CData/*1:0*/ top__DOT__cpu__DOT__cache__DOT__bo;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__hit_way;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__is_output_valid_temp;
        CData/*1:0*/ top__DOT__cpu__DOT__cache__DOT__current_state;
        CData/*1:0*/ top__DOT__cpu__DOT__cache__DOT__next_state;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__flip_LRU;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__cache_write;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__is_dmem_input_valid;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__dmem_read;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__dmem_write;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__cache_alloc;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__cache_clean;
        CData/*1:0*/ top__DOT__cpu__DOT__cache__DOT__bo_mux__DOT__control;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__reset;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__clk;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__is_input_valid;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__mem_read;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__mem_write;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__is_output_valid;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__mem_ready;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT___mem_read;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT___mem_write;
        CData/*0:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__request_arrived;
        CData/*0:0*/ top__DOT__cpu__DOT__mem_to_reg_mux__DOT__Enable;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __VactDidInit;
        CData/*0:0*/ __VactContinue;
        IData/*31:0*/ top__DOT__cpu__DOT__Cache_d_out;
        IData/*31:0*/ top__DOT__cpu__DOT__forwardA_mux_out;
        IData/*31:0*/ top__DOT__cpu__DOT__forwardB_mux_out;
        IData/*31:0*/ top__DOT__cpu__DOT__next_pc;
        IData/*31:0*/ top__DOT__cpu__DOT__current_pc;
        IData/*31:0*/ top__DOT__cpu__DOT__dout;
        IData/*31:0*/ top__DOT__cpu__DOT__actual_pc;
        IData/*31:0*/ top__DOT__cpu__DOT__pred_pc;
        IData/*31:0*/ top__DOT__cpu__DOT__rd_din;
        IData/*31:0*/ top__DOT__cpu__DOT__rs1_dout;
    };
    struct {
        IData/*31:0*/ top__DOT__cpu__DOT__rs2_dout;
        IData/*31:0*/ top__DOT__cpu__DOT__rs1_17;
        IData/*31:0*/ top__DOT__cpu__DOT__imm_gen_out;
        IData/*31:0*/ top__DOT__cpu__DOT__alu_result;
        IData/*31:0*/ top__DOT__cpu__DOT__ALUSrc_A_mux_out;
        IData/*31:0*/ top__DOT__cpu__DOT__ALUSrc_B_mux_out;
        IData/*31:0*/ top__DOT__cpu__DOT__mem_data_out;
        IData/*31:0*/ top__DOT__cpu__DOT__IF_ID_inst;
        IData/*31:0*/ top__DOT__cpu__DOT__IF_ID_PC;
        IData/*31:0*/ top__DOT__cpu__DOT__IF_ID_pred_PC;
        IData/*31:0*/ top__DOT__cpu__DOT__ID_EX_rs1_data;
        IData/*31:0*/ top__DOT__cpu__DOT__ID_EX_rs2_data;
        IData/*31:0*/ top__DOT__cpu__DOT__ID_EX_imm;
        IData/*31:0*/ top__DOT__cpu__DOT__ID_EX_ALU_ctrl_unit_input;
        IData/*31:0*/ top__DOT__cpu__DOT__ID_EX_PC;
        IData/*31:0*/ top__DOT__cpu__DOT__ID_EX_pred_PC;
        IData/*31:0*/ top__DOT__cpu__DOT__EX_MEM_alu_out;
        IData/*31:0*/ top__DOT__cpu__DOT__EX_MEM_dmem_data;
        IData/*31:0*/ top__DOT__cpu__DOT__MEM_WB_mem_to_reg_src_1;
        IData/*31:0*/ top__DOT__cpu__DOT__MEM_WB_mem_to_reg_src_2;
        IData/*31:0*/ top__DOT__cpu__DOT__pc__DOT__next_pc;
        IData/*31:0*/ top__DOT__cpu__DOT__pc__DOT__current_pc;
        IData/*31:0*/ top__DOT__cpu__DOT__branch_predictor__DOT__current_pc;
        IData/*31:0*/ top__DOT__cpu__DOT__branch_predictor__DOT__ID_EX_PC;
        IData/*31:0*/ top__DOT__cpu__DOT__branch_predictor__DOT__actual_pc;
        IData/*31:0*/ top__DOT__cpu__DOT__branch_predictor__DOT__pred_pc;
        IData/*31:0*/ top__DOT__cpu__DOT__branch_predictor__DOT__i;
        IData/*24:0*/ top__DOT__cpu__DOT__branch_predictor__DOT__tag;
        IData/*31:0*/ top__DOT__cpu__DOT__branch_predictor__DOT__not_taken_pc;
        IData/*24:0*/ top__DOT__cpu__DOT__branch_predictor__DOT__ID_EX_tag;
        IData/*31:0*/ top__DOT__cpu__DOT__branch_predictor__DOT__Add_PC_4_NT__DOT__in_1;
        IData/*31:0*/ top__DOT__cpu__DOT__branch_predictor__DOT__Add_PC_4_NT__DOT__in_2;
        IData/*31:0*/ top__DOT__cpu__DOT__branch_predictor__DOT__Add_PC_4_NT__DOT__out;
        IData/*31:0*/ top__DOT__cpu__DOT__branch_predictor__DOT__pred_taken_mux__DOT__A;
        IData/*31:0*/ top__DOT__cpu__DOT__branch_predictor__DOT__pred_taken_mux__DOT__B;
        IData/*31:0*/ top__DOT__cpu__DOT__branch_predictor__DOT__pred_taken_mux__DOT__C;
        IData/*31:0*/ top__DOT__cpu__DOT__miss_mux__DOT__A;
        IData/*31:0*/ top__DOT__cpu__DOT__miss_mux__DOT__B;
        IData/*31:0*/ top__DOT__cpu__DOT__miss_mux__DOT__C;
        IData/*31:0*/ top__DOT__cpu__DOT__imem__DOT__addr;
        IData/*31:0*/ top__DOT__cpu__DOT__imem__DOT__dout;
        IData/*31:0*/ top__DOT__cpu__DOT__imem__DOT__i;
        IData/*31:0*/ top__DOT__cpu__DOT__imem__DOT__imem_addr;
        IData/*31:0*/ top__DOT__cpu__DOT__reg_file__DOT__rd_din;
        IData/*31:0*/ top__DOT__cpu__DOT__reg_file__DOT__rs1_dout;
        IData/*31:0*/ top__DOT__cpu__DOT__reg_file__DOT__rs2_dout;
        IData/*31:0*/ top__DOT__cpu__DOT__reg_file__DOT__i;
        IData/*31:0*/ top__DOT__cpu__DOT__imm_gen__DOT__part_of_inst;
        IData/*31:0*/ top__DOT__cpu__DOT__imm_gen__DOT__imm_gen_out;
        IData/*31:0*/ top__DOT__cpu__DOT__imm_gen__DOT__i;
        IData/*31:0*/ top__DOT__cpu__DOT__forwardA_mux__DOT__A;
        IData/*31:0*/ top__DOT__cpu__DOT__forwardA_mux__DOT__B;
        IData/*31:0*/ top__DOT__cpu__DOT__forwardA_mux__DOT__C;
        IData/*31:0*/ top__DOT__cpu__DOT__forwardA_mux__DOT__D;
        IData/*31:0*/ top__DOT__cpu__DOT__forwardA_mux__DOT__result;
        IData/*31:0*/ top__DOT__cpu__DOT__forwardB_mux__DOT__A;
        IData/*31:0*/ top__DOT__cpu__DOT__forwardB_mux__DOT__B;
        IData/*31:0*/ top__DOT__cpu__DOT__forwardB_mux__DOT__C;
        IData/*31:0*/ top__DOT__cpu__DOT__forwardB_mux__DOT__D;
        IData/*31:0*/ top__DOT__cpu__DOT__forwardB_mux__DOT__result;
        IData/*31:0*/ top__DOT__cpu__DOT__ALUSrc_A_mux__DOT__A;
        IData/*31:0*/ top__DOT__cpu__DOT__ALUSrc_A_mux__DOT__B;
        IData/*31:0*/ top__DOT__cpu__DOT__ALUSrc_A_mux__DOT__C;
        IData/*31:0*/ top__DOT__cpu__DOT__ALUSrc_B_mux__DOT__A;
    };
    struct {
        IData/*31:0*/ top__DOT__cpu__DOT__ALUSrc_B_mux__DOT__B;
        IData/*31:0*/ top__DOT__cpu__DOT__ALUSrc_B_mux__DOT__C;
        IData/*31:0*/ top__DOT__cpu__DOT__ALUSrc_B_mux__DOT__D;
        IData/*31:0*/ top__DOT__cpu__DOT__ALUSrc_B_mux__DOT__result;
        IData/*31:0*/ top__DOT__cpu__DOT__alu_ctrl_unit__DOT__part_of_inst;
        IData/*31:0*/ top__DOT__cpu__DOT__alu__DOT__alu_in_1;
        IData/*31:0*/ top__DOT__cpu__DOT__alu__DOT__alu_in_2;
        IData/*31:0*/ top__DOT__cpu__DOT__alu__DOT__alu_result;
        IData/*31:0*/ top__DOT__cpu__DOT__branch_calculator__DOT__ID_EX_PC;
        IData/*31:0*/ top__DOT__cpu__DOT__branch_calculator__DOT__ID_EX_rs1_data;
        IData/*31:0*/ top__DOT__cpu__DOT__branch_calculator__DOT__ID_EX_imm;
        IData/*31:0*/ top__DOT__cpu__DOT__branch_calculator__DOT__actual_pc;
        IData/*31:0*/ top__DOT__cpu__DOT__branch_calculator__DOT__is_jalr_mux_out;
        IData/*31:0*/ top__DOT__cpu__DOT__branch_calculator__DOT__jump_addr;
        IData/*31:0*/ top__DOT__cpu__DOT__branch_calculator__DOT__is_jalr_mux__DOT__A;
        IData/*31:0*/ top__DOT__cpu__DOT__branch_calculator__DOT__is_jalr_mux__DOT__B;
        IData/*31:0*/ top__DOT__cpu__DOT__branch_calculator__DOT__is_jalr_mux__DOT__C;
        IData/*31:0*/ top__DOT__cpu__DOT__branch_calculator__DOT__Add_imm__DOT__in_1;
        IData/*31:0*/ top__DOT__cpu__DOT__branch_calculator__DOT__Add_imm__DOT__in_2;
        IData/*31:0*/ top__DOT__cpu__DOT__branch_calculator__DOT__Add_imm__DOT__out;
        IData/*31:0*/ top__DOT__cpu__DOT__Miss_Detection_Unit__DOT__ID_EX_pred_PC;
        IData/*31:0*/ top__DOT__cpu__DOT__Miss_Detection_Unit__DOT__actual_pc;
        IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__addr;
        IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__din;
        IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__dout;
        IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__i;
        VlWide<4>/*127:0*/ top__DOT__cpu__DOT__cache__DOT__dout_dmem;
        IData/*24:0*/ top__DOT__cpu__DOT__cache__DOT__tag;
        VlWide<4>/*127:0*/ top__DOT__cpu__DOT__cache__DOT__data_BUS;
        IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__addr_dmem;
        VlWide<4>/*127:0*/ top__DOT__cpu__DOT__cache__DOT__din_dmem;
        IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT____Vcellinp__data_mem__addr;
        IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__bo_mux__DOT__A;
        IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__bo_mux__DOT__B;
        IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__bo_mux__DOT__C;
        IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__bo_mux__DOT__D;
        IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__bo_mux__DOT__result;
        IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__addr;
        VlWide<4>/*127:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__din;
        VlWide<4>/*127:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__dout;
        IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__i;
        IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__delay_counter;
        IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT___mem_addr;
        VlWide<4>/*127:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT___din;
        IData/*31:0*/ top__DOT__cpu__DOT__mem_to_reg_mux__DOT__A;
        IData/*31:0*/ top__DOT__cpu__DOT__mem_to_reg_mux__DOT__B;
        IData/*31:0*/ top__DOT__cpu__DOT__mem_to_reg_mux__DOT__C;
        IData/*31:0*/ __VactIterCount;
        VL_OUT(print_reg[32],31,0);
        VlUnpacked<IData/*31:0*/, 32> top__DOT__print_reg;
        VlUnpacked<IData/*31:0*/, 32> top__DOT__cpu__DOT__print_reg;
        VlUnpacked<IData/*31:0*/, 32> top__DOT__cpu__DOT__branch_predictor__DOT__BTB;
        VlUnpacked<IData/*24:0*/, 32> top__DOT__cpu__DOT__branch_predictor__DOT__TAG_table;
        VlUnpacked<CData/*1:0*/, 32> top__DOT__cpu__DOT__branch_predictor__DOT__PHT;
        VlUnpacked<IData/*31:0*/, 16384> top__DOT__cpu__DOT__imem__DOT__mem;
        VlUnpacked<IData/*31:0*/, 32> top__DOT__cpu__DOT__reg_file__DOT__print_reg;
        VlUnpacked<IData/*31:0*/, 32> top__DOT__cpu__DOT__reg_file__DOT__rf;
        VlUnpacked<VlUnpacked<IData/*24:0*/, 2>, 8> top__DOT__cpu__DOT__cache__DOT__TagBank;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 8> top__DOT__cpu__DOT__cache__DOT__is_valid;
        VlUnpacked<VlUnpacked<CData/*0:0*/, 2>, 8> top__DOT__cpu__DOT__cache__DOT__is_dirty;
        VlUnpacked<VlUnpacked<VlWide<4>/*127:0*/, 2>, 8> top__DOT__cpu__DOT__cache__DOT__DataBank;
        VlUnpacked<CData/*0:0*/, 8> top__DOT__cpu__DOT__cache__DOT__LRU;
        VlUnpacked<VlWide<4>/*127:0*/, 16384> top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__mem;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<2> __VactTriggered;
    VlTriggerVec<2> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__pc__DOT__word_size = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__branch_predictor__DOT__tag_size = 0x00000019U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__branch_predictor__DOT__idx_size = 5U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__branch_predictor__DOT__entry_size = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__branch_predictor__DOT__Add_PC_4_NT__DOT__data_width = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__branch_predictor__DOT__pred_taken_mux__DOT__data_width = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__miss_mux__DOT__data_width = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__imem__DOT__MEM_DEPTH = 0x00004000U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__forwardA_mux__DOT__data_width = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__forwardB_mux__DOT__data_width = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__ALUSrc_A_mux__DOT__data_width = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__ALUSrc_B_mux__DOT__data_width = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__alu__DOT__data_width = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__branch_calculator__DOT__is_jalr_mux__DOT__data_width = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__branch_calculator__DOT__Add_imm__DOT__data_width = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__LINE_SIZE = 0x00000010U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__NUM_SETS = 8U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__NUM_WAYS = 2U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__TAG_SIZE = 0x00000019U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__IDX_SIZE = 3U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__B_OFFSET = 2U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__bo_mux__DOT__data_width = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__MEM_DEPTH = 0x00004000U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__DELAY = 0x00000032U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__BLOCK_SIZE = 0x00000010U;
    static constexpr IData/*31:0*/ top__DOT__cpu__DOT__mem_to_reg_mux__DOT__data_width = 0x00000020U;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
