// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vtop__Syms.h"


void Vtop___024root__trace_chg_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

void Vtop___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_chg_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    if (VL_UNLIKELY(!vlSymsp->__Vm_activity)) return;
    // Body
    Vtop___024root__trace_chg_0_sub_0((&vlSymsp->TOP), bufp);
}

void Vtop___024root__trace_chg_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_chg_0_sub_0\n"); );
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode + 1);
    // Body
    bufp->chgBit(oldp+0,(vlSelf->reset));
    bufp->chgBit(oldp+1,(vlSelf->clk));
    bufp->chgBit(oldp+2,(vlSelf->is_halted));
    bufp->chgIData(oldp+3,(vlSelf->print_reg[0]),32);
    bufp->chgIData(oldp+4,(vlSelf->print_reg[1]),32);
    bufp->chgIData(oldp+5,(vlSelf->print_reg[2]),32);
    bufp->chgIData(oldp+6,(vlSelf->print_reg[3]),32);
    bufp->chgIData(oldp+7,(vlSelf->print_reg[4]),32);
    bufp->chgIData(oldp+8,(vlSelf->print_reg[5]),32);
    bufp->chgIData(oldp+9,(vlSelf->print_reg[6]),32);
    bufp->chgIData(oldp+10,(vlSelf->print_reg[7]),32);
    bufp->chgIData(oldp+11,(vlSelf->print_reg[8]),32);
    bufp->chgIData(oldp+12,(vlSelf->print_reg[9]),32);
    bufp->chgIData(oldp+13,(vlSelf->print_reg[10]),32);
    bufp->chgIData(oldp+14,(vlSelf->print_reg[11]),32);
    bufp->chgIData(oldp+15,(vlSelf->print_reg[12]),32);
    bufp->chgIData(oldp+16,(vlSelf->print_reg[13]),32);
    bufp->chgIData(oldp+17,(vlSelf->print_reg[14]),32);
    bufp->chgIData(oldp+18,(vlSelf->print_reg[15]),32);
    bufp->chgIData(oldp+19,(vlSelf->print_reg[16]),32);
    bufp->chgIData(oldp+20,(vlSelf->print_reg[17]),32);
    bufp->chgIData(oldp+21,(vlSelf->print_reg[18]),32);
    bufp->chgIData(oldp+22,(vlSelf->print_reg[19]),32);
    bufp->chgIData(oldp+23,(vlSelf->print_reg[20]),32);
    bufp->chgIData(oldp+24,(vlSelf->print_reg[21]),32);
    bufp->chgIData(oldp+25,(vlSelf->print_reg[22]),32);
    bufp->chgIData(oldp+26,(vlSelf->print_reg[23]),32);
    bufp->chgIData(oldp+27,(vlSelf->print_reg[24]),32);
    bufp->chgIData(oldp+28,(vlSelf->print_reg[25]),32);
    bufp->chgIData(oldp+29,(vlSelf->print_reg[26]),32);
    bufp->chgIData(oldp+30,(vlSelf->print_reg[27]),32);
    bufp->chgIData(oldp+31,(vlSelf->print_reg[28]),32);
    bufp->chgIData(oldp+32,(vlSelf->print_reg[29]),32);
    bufp->chgIData(oldp+33,(vlSelf->print_reg[30]),32);
    bufp->chgIData(oldp+34,(vlSelf->print_reg[31]),32);
    bufp->chgBit(oldp+35,(vlSelf->top__DOT__reset));
    bufp->chgBit(oldp+36,(vlSelf->top__DOT__clk));
    bufp->chgBit(oldp+37,(vlSelf->top__DOT__is_halted));
    bufp->chgIData(oldp+38,(vlSelf->top__DOT__print_reg[0]),32);
    bufp->chgIData(oldp+39,(vlSelf->top__DOT__print_reg[1]),32);
    bufp->chgIData(oldp+40,(vlSelf->top__DOT__print_reg[2]),32);
    bufp->chgIData(oldp+41,(vlSelf->top__DOT__print_reg[3]),32);
    bufp->chgIData(oldp+42,(vlSelf->top__DOT__print_reg[4]),32);
    bufp->chgIData(oldp+43,(vlSelf->top__DOT__print_reg[5]),32);
    bufp->chgIData(oldp+44,(vlSelf->top__DOT__print_reg[6]),32);
    bufp->chgIData(oldp+45,(vlSelf->top__DOT__print_reg[7]),32);
    bufp->chgIData(oldp+46,(vlSelf->top__DOT__print_reg[8]),32);
    bufp->chgIData(oldp+47,(vlSelf->top__DOT__print_reg[9]),32);
    bufp->chgIData(oldp+48,(vlSelf->top__DOT__print_reg[10]),32);
    bufp->chgIData(oldp+49,(vlSelf->top__DOT__print_reg[11]),32);
    bufp->chgIData(oldp+50,(vlSelf->top__DOT__print_reg[12]),32);
    bufp->chgIData(oldp+51,(vlSelf->top__DOT__print_reg[13]),32);
    bufp->chgIData(oldp+52,(vlSelf->top__DOT__print_reg[14]),32);
    bufp->chgIData(oldp+53,(vlSelf->top__DOT__print_reg[15]),32);
    bufp->chgIData(oldp+54,(vlSelf->top__DOT__print_reg[16]),32);
    bufp->chgIData(oldp+55,(vlSelf->top__DOT__print_reg[17]),32);
    bufp->chgIData(oldp+56,(vlSelf->top__DOT__print_reg[18]),32);
    bufp->chgIData(oldp+57,(vlSelf->top__DOT__print_reg[19]),32);
    bufp->chgIData(oldp+58,(vlSelf->top__DOT__print_reg[20]),32);
    bufp->chgIData(oldp+59,(vlSelf->top__DOT__print_reg[21]),32);
    bufp->chgIData(oldp+60,(vlSelf->top__DOT__print_reg[22]),32);
    bufp->chgIData(oldp+61,(vlSelf->top__DOT__print_reg[23]),32);
    bufp->chgIData(oldp+62,(vlSelf->top__DOT__print_reg[24]),32);
    bufp->chgIData(oldp+63,(vlSelf->top__DOT__print_reg[25]),32);
    bufp->chgIData(oldp+64,(vlSelf->top__DOT__print_reg[26]),32);
    bufp->chgIData(oldp+65,(vlSelf->top__DOT__print_reg[27]),32);
    bufp->chgIData(oldp+66,(vlSelf->top__DOT__print_reg[28]),32);
    bufp->chgIData(oldp+67,(vlSelf->top__DOT__print_reg[29]),32);
    bufp->chgIData(oldp+68,(vlSelf->top__DOT__print_reg[30]),32);
    bufp->chgIData(oldp+69,(vlSelf->top__DOT__print_reg[31]),32);
    bufp->chgBit(oldp+70,(vlSelf->top__DOT__cpu__DOT__reset));
    bufp->chgBit(oldp+71,(vlSelf->top__DOT__cpu__DOT__clk));
    bufp->chgBit(oldp+72,(vlSelf->top__DOT__cpu__DOT__is_halted));
    bufp->chgIData(oldp+73,(vlSelf->top__DOT__cpu__DOT__print_reg[0]),32);
    bufp->chgIData(oldp+74,(vlSelf->top__DOT__cpu__DOT__print_reg[1]),32);
    bufp->chgIData(oldp+75,(vlSelf->top__DOT__cpu__DOT__print_reg[2]),32);
    bufp->chgIData(oldp+76,(vlSelf->top__DOT__cpu__DOT__print_reg[3]),32);
    bufp->chgIData(oldp+77,(vlSelf->top__DOT__cpu__DOT__print_reg[4]),32);
    bufp->chgIData(oldp+78,(vlSelf->top__DOT__cpu__DOT__print_reg[5]),32);
    bufp->chgIData(oldp+79,(vlSelf->top__DOT__cpu__DOT__print_reg[6]),32);
    bufp->chgIData(oldp+80,(vlSelf->top__DOT__cpu__DOT__print_reg[7]),32);
    bufp->chgIData(oldp+81,(vlSelf->top__DOT__cpu__DOT__print_reg[8]),32);
    bufp->chgIData(oldp+82,(vlSelf->top__DOT__cpu__DOT__print_reg[9]),32);
    bufp->chgIData(oldp+83,(vlSelf->top__DOT__cpu__DOT__print_reg[10]),32);
    bufp->chgIData(oldp+84,(vlSelf->top__DOT__cpu__DOT__print_reg[11]),32);
    bufp->chgIData(oldp+85,(vlSelf->top__DOT__cpu__DOT__print_reg[12]),32);
    bufp->chgIData(oldp+86,(vlSelf->top__DOT__cpu__DOT__print_reg[13]),32);
    bufp->chgIData(oldp+87,(vlSelf->top__DOT__cpu__DOT__print_reg[14]),32);
    bufp->chgIData(oldp+88,(vlSelf->top__DOT__cpu__DOT__print_reg[15]),32);
    bufp->chgIData(oldp+89,(vlSelf->top__DOT__cpu__DOT__print_reg[16]),32);
    bufp->chgIData(oldp+90,(vlSelf->top__DOT__cpu__DOT__print_reg[17]),32);
    bufp->chgIData(oldp+91,(vlSelf->top__DOT__cpu__DOT__print_reg[18]),32);
    bufp->chgIData(oldp+92,(vlSelf->top__DOT__cpu__DOT__print_reg[19]),32);
    bufp->chgIData(oldp+93,(vlSelf->top__DOT__cpu__DOT__print_reg[20]),32);
    bufp->chgIData(oldp+94,(vlSelf->top__DOT__cpu__DOT__print_reg[21]),32);
    bufp->chgIData(oldp+95,(vlSelf->top__DOT__cpu__DOT__print_reg[22]),32);
    bufp->chgIData(oldp+96,(vlSelf->top__DOT__cpu__DOT__print_reg[23]),32);
    bufp->chgIData(oldp+97,(vlSelf->top__DOT__cpu__DOT__print_reg[24]),32);
    bufp->chgIData(oldp+98,(vlSelf->top__DOT__cpu__DOT__print_reg[25]),32);
    bufp->chgIData(oldp+99,(vlSelf->top__DOT__cpu__DOT__print_reg[26]),32);
    bufp->chgIData(oldp+100,(vlSelf->top__DOT__cpu__DOT__print_reg[27]),32);
    bufp->chgIData(oldp+101,(vlSelf->top__DOT__cpu__DOT__print_reg[28]),32);
    bufp->chgIData(oldp+102,(vlSelf->top__DOT__cpu__DOT__print_reg[29]),32);
    bufp->chgIData(oldp+103,(vlSelf->top__DOT__cpu__DOT__print_reg[30]),32);
    bufp->chgIData(oldp+104,(vlSelf->top__DOT__cpu__DOT__print_reg[31]),32);
    bufp->chgBit(oldp+105,(vlSelf->top__DOT__cpu__DOT__PCWrite));
    bufp->chgBit(oldp+106,(vlSelf->top__DOT__cpu__DOT__is_hazard));
    bufp->chgBit(oldp+107,(vlSelf->top__DOT__cpu__DOT__IF_ID_inst_write));
    bufp->chgBit(oldp+108,(vlSelf->top__DOT__cpu__DOT__is_hit));
    bufp->chgBit(oldp+109,(vlSelf->top__DOT__cpu__DOT__is_output_valid));
    bufp->chgBit(oldp+110,(vlSelf->top__DOT__cpu__DOT__is_input_valid));
    bufp->chgBit(oldp+111,(vlSelf->top__DOT__cpu__DOT__mem_rw));
    bufp->chgIData(oldp+112,(vlSelf->top__DOT__cpu__DOT__Cache_d_out),32);
    bufp->chgBit(oldp+113,(vlSelf->top__DOT__cpu__DOT__CacheStall));
    bufp->chgBit(oldp+114,(vlSelf->top__DOT__cpu__DOT__is_ecall));
    bufp->chgBit(oldp+115,(vlSelf->top__DOT__cpu__DOT__mem_read));
    bufp->chgBit(oldp+116,(vlSelf->top__DOT__cpu__DOT__mem_to_reg));
    bufp->chgBit(oldp+117,(vlSelf->top__DOT__cpu__DOT__mem_write));
    bufp->chgBit(oldp+118,(vlSelf->top__DOT__cpu__DOT__write_enable));
    bufp->chgBit(oldp+119,(vlSelf->top__DOT__cpu__DOT__pc_to_reg));
    bufp->chgBit(oldp+120,(vlSelf->top__DOT__cpu__DOT__is_jal));
    bufp->chgBit(oldp+121,(vlSelf->top__DOT__cpu__DOT__is_jalr));
    bufp->chgBit(oldp+122,(vlSelf->top__DOT__cpu__DOT__branch));
    bufp->chgBit(oldp+123,(vlSelf->top__DOT__cpu__DOT__actual_taken));
    bufp->chgBit(oldp+124,(vlSelf->top__DOT__cpu__DOT__pred_taken));
    bufp->chgBit(oldp+125,(vlSelf->top__DOT__cpu__DOT__update_B_history));
    bufp->chgBit(oldp+126,(vlSelf->top__DOT__cpu__DOT__update_B_target));
    bufp->chgCData(oldp+127,(vlSelf->top__DOT__cpu__DOT__alu_src_B),2);
    bufp->chgCData(oldp+128,(vlSelf->top__DOT__cpu__DOT__forwardA),2);
    bufp->chgCData(oldp+129,(vlSelf->top__DOT__cpu__DOT__forwardB),2);
    bufp->chgIData(oldp+130,(vlSelf->top__DOT__cpu__DOT__forwardA_mux_out),32);
    bufp->chgIData(oldp+131,(vlSelf->top__DOT__cpu__DOT__forwardB_mux_out),32);
    bufp->chgIData(oldp+132,(vlSelf->top__DOT__cpu__DOT__next_pc),32);
    bufp->chgIData(oldp+133,(vlSelf->top__DOT__cpu__DOT__current_pc),32);
    bufp->chgIData(oldp+134,(vlSelf->top__DOT__cpu__DOT__dout),32);
    bufp->chgIData(oldp+135,(vlSelf->top__DOT__cpu__DOT__actual_pc),32);
    bufp->chgIData(oldp+136,(vlSelf->top__DOT__cpu__DOT__pred_pc),32);
    bufp->chgIData(oldp+137,(vlSelf->top__DOT__cpu__DOT__rd_din),32);
    bufp->chgIData(oldp+138,(vlSelf->top__DOT__cpu__DOT__rs1_dout),32);
    bufp->chgIData(oldp+139,(vlSelf->top__DOT__cpu__DOT__rs2_dout),32);
    bufp->chgIData(oldp+140,(vlSelf->top__DOT__cpu__DOT__rs1_17),32);
    bufp->chgCData(oldp+141,(vlSelf->top__DOT__cpu__DOT__rs1_in),5);
    bufp->chgIData(oldp+142,(vlSelf->top__DOT__cpu__DOT__imm_gen_out),32);
    bufp->chgIData(oldp+143,(vlSelf->top__DOT__cpu__DOT__alu_result),32);
    bufp->chgIData(oldp+144,(vlSelf->top__DOT__cpu__DOT__ALUSrc_A_mux_out),32);
    bufp->chgIData(oldp+145,(vlSelf->top__DOT__cpu__DOT__ALUSrc_B_mux_out),32);
    bufp->chgBit(oldp+146,(vlSelf->top__DOT__cpu__DOT__alu_bcond));
    bufp->chgCData(oldp+147,(vlSelf->top__DOT__cpu__DOT__alu_op),4);
    bufp->chgIData(oldp+148,(vlSelf->top__DOT__cpu__DOT__mem_data_out),32);
    bufp->chgBit(oldp+149,(vlSelf->top__DOT__cpu__DOT__miss));
    bufp->chgIData(oldp+150,(vlSelf->top__DOT__cpu__DOT__IF_ID_inst),32);
    bufp->chgIData(oldp+151,(vlSelf->top__DOT__cpu__DOT__IF_ID_PC),32);
    bufp->chgIData(oldp+152,(vlSelf->top__DOT__cpu__DOT__IF_ID_pred_PC),32);
    bufp->chgBit(oldp+153,(vlSelf->top__DOT__cpu__DOT__IF_ID_miss));
    bufp->chgBit(oldp+154,(vlSelf->top__DOT__cpu__DOT__IF_ID_pred_taken));
    bufp->chgCData(oldp+155,(vlSelf->top__DOT__cpu__DOT__ID_EX_alu_src_B),2);
    bufp->chgBit(oldp+156,(vlSelf->top__DOT__cpu__DOT__ID_EX_is_jal));
    bufp->chgBit(oldp+157,(vlSelf->top__DOT__cpu__DOT__ID_EX_is_jalr));
    bufp->chgBit(oldp+158,(vlSelf->top__DOT__cpu__DOT__ID_EX_branch));
    bufp->chgBit(oldp+159,(vlSelf->top__DOT__cpu__DOT__ID_EX_mem_write));
    bufp->chgBit(oldp+160,(vlSelf->top__DOT__cpu__DOT__ID_EX_mem_read));
    bufp->chgBit(oldp+161,(vlSelf->top__DOT__cpu__DOT__ID_EX_mem_to_reg));
    bufp->chgBit(oldp+162,(vlSelf->top__DOT__cpu__DOT__ID_EX_reg_write));
    bufp->chgBit(oldp+163,(vlSelf->top__DOT__cpu__DOT__ID_EX_is_halted));
    bufp->chgBit(oldp+164,(vlSelf->top__DOT__cpu__DOT__ID_EX_pc_to_reg));
    bufp->chgCData(oldp+165,(vlSelf->top__DOT__cpu__DOT__ID_EX_rs1),5);
    bufp->chgCData(oldp+166,(vlSelf->top__DOT__cpu__DOT__ID_EX_rs2),5);
    bufp->chgIData(oldp+167,(vlSelf->top__DOT__cpu__DOT__ID_EX_rs1_data),32);
    bufp->chgIData(oldp+168,(vlSelf->top__DOT__cpu__DOT__ID_EX_rs2_data),32);
    bufp->chgIData(oldp+169,(vlSelf->top__DOT__cpu__DOT__ID_EX_imm),32);
    bufp->chgIData(oldp+170,(vlSelf->top__DOT__cpu__DOT__ID_EX_ALU_ctrl_unit_input),32);
    bufp->chgCData(oldp+171,(vlSelf->top__DOT__cpu__DOT__ID_EX_rd),5);
    bufp->chgIData(oldp+172,(vlSelf->top__DOT__cpu__DOT__ID_EX_PC),32);
    bufp->chgIData(oldp+173,(vlSelf->top__DOT__cpu__DOT__ID_EX_pred_PC),32);
    bufp->chgBit(oldp+174,(vlSelf->top__DOT__cpu__DOT__ID_EX_pred_taken));
    bufp->chgBit(oldp+175,(vlSelf->top__DOT__cpu__DOT__EX_MEM_mem_write));
    bufp->chgBit(oldp+176,(vlSelf->top__DOT__cpu__DOT__EX_MEM_mem_read));
    bufp->chgBit(oldp+177,(vlSelf->top__DOT__cpu__DOT__EX_MEM_is_halted));
    bufp->chgBit(oldp+178,(vlSelf->top__DOT__cpu__DOT__EX_MEM_pc_to_reg));
    bufp->chgBit(oldp+179,(vlSelf->top__DOT__cpu__DOT__EX_MEM_mem_to_reg));
    bufp->chgBit(oldp+180,(vlSelf->top__DOT__cpu__DOT__EX_MEM_reg_write));
    bufp->chgIData(oldp+181,(vlSelf->top__DOT__cpu__DOT__EX_MEM_alu_out),32);
    bufp->chgIData(oldp+182,(vlSelf->top__DOT__cpu__DOT__EX_MEM_dmem_data),32);
    bufp->chgCData(oldp+183,(vlSelf->top__DOT__cpu__DOT__EX_MEM_rd),5);
    bufp->chgBit(oldp+184,(vlSelf->top__DOT__cpu__DOT__MEM_WB_mem_to_reg));
    bufp->chgBit(oldp+185,(vlSelf->top__DOT__cpu__DOT__MEM_WB_reg_write));
    bufp->chgBit(oldp+186,(vlSelf->top__DOT__cpu__DOT__MEM_WB_is_halted));
    bufp->chgBit(oldp+187,(vlSelf->top__DOT__cpu__DOT__MEM_WB_pc_to_reg));
    bufp->chgIData(oldp+188,(vlSelf->top__DOT__cpu__DOT__MEM_WB_mem_to_reg_src_1),32);
    bufp->chgIData(oldp+189,(vlSelf->top__DOT__cpu__DOT__MEM_WB_mem_to_reg_src_2),32);
    bufp->chgCData(oldp+190,(vlSelf->top__DOT__cpu__DOT__MEM_WB_rd),5);
    bufp->chgIData(oldp+191,(vlSelf->top__DOT__cpu__DOT__ALUSrc_A_mux__DOT__A),32);
    bufp->chgIData(oldp+192,(vlSelf->top__DOT__cpu__DOT__ALUSrc_A_mux__DOT__B),32);
    bufp->chgBit(oldp+193,(vlSelf->top__DOT__cpu__DOT__ALUSrc_A_mux__DOT__Enable));
    bufp->chgIData(oldp+194,(vlSelf->top__DOT__cpu__DOT__ALUSrc_A_mux__DOT__C),32);
    bufp->chgIData(oldp+195,(vlSelf->top__DOT__cpu__DOT__ALUSrc_B_mux__DOT__A),32);
    bufp->chgIData(oldp+196,(vlSelf->top__DOT__cpu__DOT__ALUSrc_B_mux__DOT__B),32);
    bufp->chgIData(oldp+197,(vlSelf->top__DOT__cpu__DOT__ALUSrc_B_mux__DOT__C),32);
    bufp->chgIData(oldp+198,(vlSelf->top__DOT__cpu__DOT__ALUSrc_B_mux__DOT__D),32);
    bufp->chgCData(oldp+199,(vlSelf->top__DOT__cpu__DOT__ALUSrc_B_mux__DOT__control),2);
    bufp->chgIData(oldp+200,(vlSelf->top__DOT__cpu__DOT__ALUSrc_B_mux__DOT__result),32);
    bufp->chgBit(oldp+201,(vlSelf->top__DOT__cpu__DOT__Miss_Detection_Unit__DOT__actual_taken));
    bufp->chgBit(oldp+202,(vlSelf->top__DOT__cpu__DOT__Miss_Detection_Unit__DOT__ID_EX_pred_taken));
    bufp->chgIData(oldp+203,(vlSelf->top__DOT__cpu__DOT__Miss_Detection_Unit__DOT__ID_EX_pred_PC),32);
    bufp->chgIData(oldp+204,(vlSelf->top__DOT__cpu__DOT__Miss_Detection_Unit__DOT__actual_pc),32);
    bufp->chgBit(oldp+205,(vlSelf->top__DOT__cpu__DOT__Miss_Detection_Unit__DOT__miss));
    bufp->chgCData(oldp+206,(vlSelf->top__DOT__cpu__DOT__alu__DOT__alu_op),4);
    bufp->chgIData(oldp+207,(vlSelf->top__DOT__cpu__DOT__alu__DOT__alu_in_1),32);
    bufp->chgIData(oldp+208,(vlSelf->top__DOT__cpu__DOT__alu__DOT__alu_in_2),32);
    bufp->chgIData(oldp+209,(vlSelf->top__DOT__cpu__DOT__alu__DOT__alu_result),32);
    bufp->chgBit(oldp+210,(vlSelf->top__DOT__cpu__DOT__alu__DOT__alu_bcond));
    bufp->chgIData(oldp+211,(vlSelf->top__DOT__cpu__DOT__alu_ctrl_unit__DOT__part_of_inst),32);
    bufp->chgCData(oldp+212,(vlSelf->top__DOT__cpu__DOT__alu_ctrl_unit__DOT__alu_op),4);
    bufp->chgCData(oldp+213,(vlSelf->top__DOT__cpu__DOT__alu_ctrl_unit__DOT__opcode),7);
    bufp->chgCData(oldp+214,(vlSelf->top__DOT__cpu__DOT__alu_ctrl_unit__DOT__funct3),3);
    bufp->chgCData(oldp+215,(vlSelf->top__DOT__cpu__DOT__alu_ctrl_unit__DOT__funct7),7);
    bufp->chgBit(oldp+216,(vlSelf->top__DOT__cpu__DOT__alu_ctrl_unit__DOT__unused));
    bufp->chgIData(oldp+217,(vlSelf->top__DOT__cpu__DOT__branch_calculator__DOT__ID_EX_PC),32);
    bufp->chgIData(oldp+218,(vlSelf->top__DOT__cpu__DOT__branch_calculator__DOT__ID_EX_rs1_data),32);
    bufp->chgIData(oldp+219,(vlSelf->top__DOT__cpu__DOT__branch_calculator__DOT__ID_EX_imm),32);
    bufp->chgBit(oldp+220,(vlSelf->top__DOT__cpu__DOT__branch_calculator__DOT__alu_bcond));
    bufp->chgBit(oldp+221,(vlSelf->top__DOT__cpu__DOT__branch_calculator__DOT__ID_EX_branch));
    bufp->chgBit(oldp+222,(vlSelf->top__DOT__cpu__DOT__branch_calculator__DOT__ID_EX_is_jal));
    bufp->chgBit(oldp+223,(vlSelf->top__DOT__cpu__DOT__branch_calculator__DOT__ID_EX_is_jalr));
    bufp->chgIData(oldp+224,(vlSelf->top__DOT__cpu__DOT__branch_calculator__DOT__actual_pc),32);
    bufp->chgBit(oldp+225,(vlSelf->top__DOT__cpu__DOT__branch_calculator__DOT__actual_taken));
    bufp->chgBit(oldp+226,(vlSelf->top__DOT__cpu__DOT__branch_calculator__DOT__update_B_history));
    bufp->chgBit(oldp+227,(vlSelf->top__DOT__cpu__DOT__branch_calculator__DOT__update_B_target));
    bufp->chgIData(oldp+228,(vlSelf->top__DOT__cpu__DOT__branch_calculator__DOT__is_jalr_mux_out),32);
    bufp->chgIData(oldp+229,(vlSelf->top__DOT__cpu__DOT__branch_calculator__DOT__jump_addr),32);
    bufp->chgIData(oldp+230,(vlSelf->top__DOT__cpu__DOT__branch_calculator__DOT__Add_imm__DOT__in_1),32);
    bufp->chgIData(oldp+231,(vlSelf->top__DOT__cpu__DOT__branch_calculator__DOT__Add_imm__DOT__in_2),32);
    bufp->chgIData(oldp+232,(vlSelf->top__DOT__cpu__DOT__branch_calculator__DOT__Add_imm__DOT__out),32);
    bufp->chgIData(oldp+233,(vlSelf->top__DOT__cpu__DOT__branch_calculator__DOT__is_jalr_mux__DOT__A),32);
    bufp->chgIData(oldp+234,(vlSelf->top__DOT__cpu__DOT__branch_calculator__DOT__is_jalr_mux__DOT__B),32);
    bufp->chgBit(oldp+235,(vlSelf->top__DOT__cpu__DOT__branch_calculator__DOT__is_jalr_mux__DOT__Enable));
    bufp->chgIData(oldp+236,(vlSelf->top__DOT__cpu__DOT__branch_calculator__DOT__is_jalr_mux__DOT__C),32);
    bufp->chgBit(oldp+237,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__reset));
    bufp->chgBit(oldp+238,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__clk));
    bufp->chgIData(oldp+239,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__current_pc),32);
    bufp->chgBit(oldp+240,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__update_B_history));
    bufp->chgBit(oldp+241,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__update_B_target));
    bufp->chgIData(oldp+242,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__ID_EX_PC),32);
    bufp->chgIData(oldp+243,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__actual_pc),32);
    bufp->chgBit(oldp+244,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__actual_taken));
    bufp->chgBit(oldp+245,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__pred_taken));
    bufp->chgIData(oldp+246,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__pred_pc),32);
    bufp->chgIData(oldp+247,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__i),32);
    bufp->chgCData(oldp+248,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__idx),5);
    bufp->chgIData(oldp+249,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__tag),25);
    bufp->chgCData(oldp+250,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__pht_idx),5);
    bufp->chgIData(oldp+251,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__not_taken_pc),32);
    bufp->chgCData(oldp+252,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__ID_EX_idx),5);
    bufp->chgIData(oldp+253,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__ID_EX_tag),25);
    bufp->chgCData(oldp+254,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__ID_EX_pht_idx),5);
    bufp->chgCData(oldp+255,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__extended_actual_taken),5);
    bufp->chgCData(oldp+256,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__BHSR),5);
    bufp->chgIData(oldp+257,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__BTB[0]),32);
    bufp->chgIData(oldp+258,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__BTB[1]),32);
    bufp->chgIData(oldp+259,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__BTB[2]),32);
    bufp->chgIData(oldp+260,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__BTB[3]),32);
    bufp->chgIData(oldp+261,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__BTB[4]),32);
    bufp->chgIData(oldp+262,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__BTB[5]),32);
    bufp->chgIData(oldp+263,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__BTB[6]),32);
    bufp->chgIData(oldp+264,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__BTB[7]),32);
    bufp->chgIData(oldp+265,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__BTB[8]),32);
    bufp->chgIData(oldp+266,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__BTB[9]),32);
    bufp->chgIData(oldp+267,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__BTB[10]),32);
    bufp->chgIData(oldp+268,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__BTB[11]),32);
    bufp->chgIData(oldp+269,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__BTB[12]),32);
    bufp->chgIData(oldp+270,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__BTB[13]),32);
    bufp->chgIData(oldp+271,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__BTB[14]),32);
    bufp->chgIData(oldp+272,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__BTB[15]),32);
    bufp->chgIData(oldp+273,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__BTB[16]),32);
    bufp->chgIData(oldp+274,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__BTB[17]),32);
    bufp->chgIData(oldp+275,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__BTB[18]),32);
    bufp->chgIData(oldp+276,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__BTB[19]),32);
    bufp->chgIData(oldp+277,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__BTB[20]),32);
    bufp->chgIData(oldp+278,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__BTB[21]),32);
    bufp->chgIData(oldp+279,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__BTB[22]),32);
    bufp->chgIData(oldp+280,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__BTB[23]),32);
    bufp->chgIData(oldp+281,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__BTB[24]),32);
    bufp->chgIData(oldp+282,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__BTB[25]),32);
    bufp->chgIData(oldp+283,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__BTB[26]),32);
    bufp->chgIData(oldp+284,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__BTB[27]),32);
    bufp->chgIData(oldp+285,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__BTB[28]),32);
    bufp->chgIData(oldp+286,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__BTB[29]),32);
    bufp->chgIData(oldp+287,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__BTB[30]),32);
    bufp->chgIData(oldp+288,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__BTB[31]),32);
    bufp->chgIData(oldp+289,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__TAG_table[0]),25);
    bufp->chgIData(oldp+290,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__TAG_table[1]),25);
    bufp->chgIData(oldp+291,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__TAG_table[2]),25);
    bufp->chgIData(oldp+292,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__TAG_table[3]),25);
    bufp->chgIData(oldp+293,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__TAG_table[4]),25);
    bufp->chgIData(oldp+294,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__TAG_table[5]),25);
    bufp->chgIData(oldp+295,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__TAG_table[6]),25);
    bufp->chgIData(oldp+296,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__TAG_table[7]),25);
    bufp->chgIData(oldp+297,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__TAG_table[8]),25);
    bufp->chgIData(oldp+298,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__TAG_table[9]),25);
    bufp->chgIData(oldp+299,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__TAG_table[10]),25);
    bufp->chgIData(oldp+300,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__TAG_table[11]),25);
    bufp->chgIData(oldp+301,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__TAG_table[12]),25);
    bufp->chgIData(oldp+302,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__TAG_table[13]),25);
    bufp->chgIData(oldp+303,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__TAG_table[14]),25);
    bufp->chgIData(oldp+304,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__TAG_table[15]),25);
    bufp->chgIData(oldp+305,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__TAG_table[16]),25);
    bufp->chgIData(oldp+306,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__TAG_table[17]),25);
    bufp->chgIData(oldp+307,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__TAG_table[18]),25);
    bufp->chgIData(oldp+308,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__TAG_table[19]),25);
    bufp->chgIData(oldp+309,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__TAG_table[20]),25);
    bufp->chgIData(oldp+310,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__TAG_table[21]),25);
    bufp->chgIData(oldp+311,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__TAG_table[22]),25);
    bufp->chgIData(oldp+312,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__TAG_table[23]),25);
    bufp->chgIData(oldp+313,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__TAG_table[24]),25);
    bufp->chgIData(oldp+314,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__TAG_table[25]),25);
    bufp->chgIData(oldp+315,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__TAG_table[26]),25);
    bufp->chgIData(oldp+316,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__TAG_table[27]),25);
    bufp->chgIData(oldp+317,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__TAG_table[28]),25);
    bufp->chgIData(oldp+318,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__TAG_table[29]),25);
    bufp->chgIData(oldp+319,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__TAG_table[30]),25);
    bufp->chgIData(oldp+320,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__TAG_table[31]),25);
    bufp->chgCData(oldp+321,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__PHT[0]),2);
    bufp->chgCData(oldp+322,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__PHT[1]),2);
    bufp->chgCData(oldp+323,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__PHT[2]),2);
    bufp->chgCData(oldp+324,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__PHT[3]),2);
    bufp->chgCData(oldp+325,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__PHT[4]),2);
    bufp->chgCData(oldp+326,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__PHT[5]),2);
    bufp->chgCData(oldp+327,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__PHT[6]),2);
    bufp->chgCData(oldp+328,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__PHT[7]),2);
    bufp->chgCData(oldp+329,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__PHT[8]),2);
    bufp->chgCData(oldp+330,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__PHT[9]),2);
    bufp->chgCData(oldp+331,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__PHT[10]),2);
    bufp->chgCData(oldp+332,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__PHT[11]),2);
    bufp->chgCData(oldp+333,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__PHT[12]),2);
    bufp->chgCData(oldp+334,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__PHT[13]),2);
    bufp->chgCData(oldp+335,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__PHT[14]),2);
    bufp->chgCData(oldp+336,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__PHT[15]),2);
    bufp->chgCData(oldp+337,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__PHT[16]),2);
    bufp->chgCData(oldp+338,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__PHT[17]),2);
    bufp->chgCData(oldp+339,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__PHT[18]),2);
    bufp->chgCData(oldp+340,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__PHT[19]),2);
    bufp->chgCData(oldp+341,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__PHT[20]),2);
    bufp->chgCData(oldp+342,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__PHT[21]),2);
    bufp->chgCData(oldp+343,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__PHT[22]),2);
    bufp->chgCData(oldp+344,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__PHT[23]),2);
    bufp->chgCData(oldp+345,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__PHT[24]),2);
    bufp->chgCData(oldp+346,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__PHT[25]),2);
    bufp->chgCData(oldp+347,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__PHT[26]),2);
    bufp->chgCData(oldp+348,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__PHT[27]),2);
    bufp->chgCData(oldp+349,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__PHT[28]),2);
    bufp->chgCData(oldp+350,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__PHT[29]),2);
    bufp->chgCData(oldp+351,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__PHT[30]),2);
    bufp->chgCData(oldp+352,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__PHT[31]),2);
    bufp->chgIData(oldp+353,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__Add_PC_4_NT__DOT__in_1),32);
    bufp->chgIData(oldp+354,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__Add_PC_4_NT__DOT__in_2),32);
    bufp->chgIData(oldp+355,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__Add_PC_4_NT__DOT__out),32);
    bufp->chgIData(oldp+356,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__pred_taken_mux__DOT__A),32);
    bufp->chgIData(oldp+357,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__pred_taken_mux__DOT__B),32);
    bufp->chgBit(oldp+358,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__pred_taken_mux__DOT__Enable));
    bufp->chgIData(oldp+359,(vlSelf->top__DOT__cpu__DOT__branch_predictor__DOT__pred_taken_mux__DOT__C),32);
    bufp->chgBit(oldp+360,(vlSelf->top__DOT__cpu__DOT__cache__DOT__reset));
    bufp->chgBit(oldp+361,(vlSelf->top__DOT__cpu__DOT__cache__DOT__clk));
    bufp->chgBit(oldp+362,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_input_valid));
    bufp->chgIData(oldp+363,(vlSelf->top__DOT__cpu__DOT__cache__DOT__addr),32);
    bufp->chgBit(oldp+364,(vlSelf->top__DOT__cpu__DOT__cache__DOT__mem_rw));
    bufp->chgIData(oldp+365,(vlSelf->top__DOT__cpu__DOT__cache__DOT__din),32);
    bufp->chgBit(oldp+366,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_output_valid));
    bufp->chgIData(oldp+367,(vlSelf->top__DOT__cpu__DOT__cache__DOT__dout),32);
    bufp->chgBit(oldp+368,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_hit));
    bufp->chgIData(oldp+369,(vlSelf->top__DOT__cpu__DOT__cache__DOT__i),32);
    bufp->chgBit(oldp+370,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_dmem_ready));
    bufp->chgBit(oldp+371,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_dmem_output_valid));
    bufp->chgCData(oldp+372,(vlSelf->top__DOT__cpu__DOT__cache__DOT__clog2),4);
    bufp->chgWData(oldp+373,(vlSelf->top__DOT__cpu__DOT__cache__DOT__dout_dmem),128);
    bufp->chgIData(oldp+377,(vlSelf->top__DOT__cpu__DOT__cache__DOT__tag),25);
    bufp->chgCData(oldp+378,(vlSelf->top__DOT__cpu__DOT__cache__DOT__idx),3);
    bufp->chgCData(oldp+379,(vlSelf->top__DOT__cpu__DOT__cache__DOT__bo),2);
    bufp->chgWData(oldp+380,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data_BUS),128);
    bufp->chgBit(oldp+384,(vlSelf->top__DOT__cpu__DOT__cache__DOT__hit_way));
    bufp->chgBit(oldp+385,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_output_valid_temp));
    bufp->chgCData(oldp+386,(vlSelf->top__DOT__cpu__DOT__cache__DOT__current_state),2);
    bufp->chgCData(oldp+387,(vlSelf->top__DOT__cpu__DOT__cache__DOT__next_state),2);
    bufp->chgIData(oldp+388,(vlSelf->top__DOT__cpu__DOT__cache__DOT__addr_dmem),32);
    bufp->chgWData(oldp+389,(vlSelf->top__DOT__cpu__DOT__cache__DOT__din_dmem),128);
    bufp->chgIData(oldp+393,(vlSelf->top__DOT__cpu__DOT__cache__DOT__TagBank
                             [0U][0U]),25);
    bufp->chgIData(oldp+394,(vlSelf->top__DOT__cpu__DOT__cache__DOT__TagBank
                             [0U][1U]),25);
    bufp->chgIData(oldp+395,(vlSelf->top__DOT__cpu__DOT__cache__DOT__TagBank
                             [1U][0U]),25);
    bufp->chgIData(oldp+396,(vlSelf->top__DOT__cpu__DOT__cache__DOT__TagBank
                             [1U][1U]),25);
    bufp->chgIData(oldp+397,(vlSelf->top__DOT__cpu__DOT__cache__DOT__TagBank
                             [2U][0U]),25);
    bufp->chgIData(oldp+398,(vlSelf->top__DOT__cpu__DOT__cache__DOT__TagBank
                             [2U][1U]),25);
    bufp->chgIData(oldp+399,(vlSelf->top__DOT__cpu__DOT__cache__DOT__TagBank
                             [3U][0U]),25);
    bufp->chgIData(oldp+400,(vlSelf->top__DOT__cpu__DOT__cache__DOT__TagBank
                             [3U][1U]),25);
    bufp->chgIData(oldp+401,(vlSelf->top__DOT__cpu__DOT__cache__DOT__TagBank
                             [4U][0U]),25);
    bufp->chgIData(oldp+402,(vlSelf->top__DOT__cpu__DOT__cache__DOT__TagBank
                             [4U][1U]),25);
    bufp->chgIData(oldp+403,(vlSelf->top__DOT__cpu__DOT__cache__DOT__TagBank
                             [5U][0U]),25);
    bufp->chgIData(oldp+404,(vlSelf->top__DOT__cpu__DOT__cache__DOT__TagBank
                             [5U][1U]),25);
    bufp->chgIData(oldp+405,(vlSelf->top__DOT__cpu__DOT__cache__DOT__TagBank
                             [6U][0U]),25);
    bufp->chgIData(oldp+406,(vlSelf->top__DOT__cpu__DOT__cache__DOT__TagBank
                             [6U][1U]),25);
    bufp->chgIData(oldp+407,(vlSelf->top__DOT__cpu__DOT__cache__DOT__TagBank
                             [7U][0U]),25);
    bufp->chgIData(oldp+408,(vlSelf->top__DOT__cpu__DOT__cache__DOT__TagBank
                             [7U][1U]),25);
    bufp->chgBit(oldp+409,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_valid
                           [0U][0U]));
    bufp->chgBit(oldp+410,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_valid
                           [0U][1U]));
    bufp->chgBit(oldp+411,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_valid
                           [1U][0U]));
    bufp->chgBit(oldp+412,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_valid
                           [1U][1U]));
    bufp->chgBit(oldp+413,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_valid
                           [2U][0U]));
    bufp->chgBit(oldp+414,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_valid
                           [2U][1U]));
    bufp->chgBit(oldp+415,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_valid
                           [3U][0U]));
    bufp->chgBit(oldp+416,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_valid
                           [3U][1U]));
    bufp->chgBit(oldp+417,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_valid
                           [4U][0U]));
    bufp->chgBit(oldp+418,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_valid
                           [4U][1U]));
    bufp->chgBit(oldp+419,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_valid
                           [5U][0U]));
    bufp->chgBit(oldp+420,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_valid
                           [5U][1U]));
    bufp->chgBit(oldp+421,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_valid
                           [6U][0U]));
    bufp->chgBit(oldp+422,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_valid
                           [6U][1U]));
    bufp->chgBit(oldp+423,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_valid
                           [7U][0U]));
    bufp->chgBit(oldp+424,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_valid
                           [7U][1U]));
    bufp->chgBit(oldp+425,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_dirty
                           [0U][0U]));
    bufp->chgBit(oldp+426,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_dirty
                           [0U][1U]));
    bufp->chgBit(oldp+427,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_dirty
                           [1U][0U]));
    bufp->chgBit(oldp+428,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_dirty
                           [1U][1U]));
    bufp->chgBit(oldp+429,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_dirty
                           [2U][0U]));
    bufp->chgBit(oldp+430,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_dirty
                           [2U][1U]));
    bufp->chgBit(oldp+431,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_dirty
                           [3U][0U]));
    bufp->chgBit(oldp+432,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_dirty
                           [3U][1U]));
    bufp->chgBit(oldp+433,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_dirty
                           [4U][0U]));
    bufp->chgBit(oldp+434,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_dirty
                           [4U][1U]));
    bufp->chgBit(oldp+435,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_dirty
                           [5U][0U]));
    bufp->chgBit(oldp+436,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_dirty
                           [5U][1U]));
    bufp->chgBit(oldp+437,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_dirty
                           [6U][0U]));
    bufp->chgBit(oldp+438,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_dirty
                           [6U][1U]));
    bufp->chgBit(oldp+439,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_dirty
                           [7U][0U]));
    bufp->chgBit(oldp+440,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_dirty
                           [7U][1U]));
    bufp->chgWData(oldp+441,(vlSelf->top__DOT__cpu__DOT__cache__DOT__DataBank
                             [0U][0U]),128);
    bufp->chgWData(oldp+445,(vlSelf->top__DOT__cpu__DOT__cache__DOT__DataBank
                             [0U][1U]),128);
    bufp->chgWData(oldp+449,(vlSelf->top__DOT__cpu__DOT__cache__DOT__DataBank
                             [1U][0U]),128);
    bufp->chgWData(oldp+453,(vlSelf->top__DOT__cpu__DOT__cache__DOT__DataBank
                             [1U][1U]),128);
    bufp->chgWData(oldp+457,(vlSelf->top__DOT__cpu__DOT__cache__DOT__DataBank
                             [2U][0U]),128);
    bufp->chgWData(oldp+461,(vlSelf->top__DOT__cpu__DOT__cache__DOT__DataBank
                             [2U][1U]),128);
    bufp->chgWData(oldp+465,(vlSelf->top__DOT__cpu__DOT__cache__DOT__DataBank
                             [3U][0U]),128);
    bufp->chgWData(oldp+469,(vlSelf->top__DOT__cpu__DOT__cache__DOT__DataBank
                             [3U][1U]),128);
    bufp->chgWData(oldp+473,(vlSelf->top__DOT__cpu__DOT__cache__DOT__DataBank
                             [4U][0U]),128);
    bufp->chgWData(oldp+477,(vlSelf->top__DOT__cpu__DOT__cache__DOT__DataBank
                             [4U][1U]),128);
    bufp->chgWData(oldp+481,(vlSelf->top__DOT__cpu__DOT__cache__DOT__DataBank
                             [5U][0U]),128);
    bufp->chgWData(oldp+485,(vlSelf->top__DOT__cpu__DOT__cache__DOT__DataBank
                             [5U][1U]),128);
    bufp->chgWData(oldp+489,(vlSelf->top__DOT__cpu__DOT__cache__DOT__DataBank
                             [6U][0U]),128);
    bufp->chgWData(oldp+493,(vlSelf->top__DOT__cpu__DOT__cache__DOT__DataBank
                             [6U][1U]),128);
    bufp->chgWData(oldp+497,(vlSelf->top__DOT__cpu__DOT__cache__DOT__DataBank
                             [7U][0U]),128);
    bufp->chgWData(oldp+501,(vlSelf->top__DOT__cpu__DOT__cache__DOT__DataBank
                             [7U][1U]),128);
    bufp->chgBit(oldp+505,(vlSelf->top__DOT__cpu__DOT__cache__DOT__LRU[0]));
    bufp->chgBit(oldp+506,(vlSelf->top__DOT__cpu__DOT__cache__DOT__LRU[1]));
    bufp->chgBit(oldp+507,(vlSelf->top__DOT__cpu__DOT__cache__DOT__LRU[2]));
    bufp->chgBit(oldp+508,(vlSelf->top__DOT__cpu__DOT__cache__DOT__LRU[3]));
    bufp->chgBit(oldp+509,(vlSelf->top__DOT__cpu__DOT__cache__DOT__LRU[4]));
    bufp->chgBit(oldp+510,(vlSelf->top__DOT__cpu__DOT__cache__DOT__LRU[5]));
    bufp->chgBit(oldp+511,(vlSelf->top__DOT__cpu__DOT__cache__DOT__LRU[6]));
    bufp->chgBit(oldp+512,(vlSelf->top__DOT__cpu__DOT__cache__DOT__LRU[7]));
    bufp->chgBit(oldp+513,(vlSelf->top__DOT__cpu__DOT__cache__DOT__flip_LRU));
    bufp->chgBit(oldp+514,(vlSelf->top__DOT__cpu__DOT__cache__DOT__cache_write));
    bufp->chgBit(oldp+515,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_dmem_input_valid));
    bufp->chgBit(oldp+516,(vlSelf->top__DOT__cpu__DOT__cache__DOT__dmem_read));
    bufp->chgBit(oldp+517,(vlSelf->top__DOT__cpu__DOT__cache__DOT__dmem_write));
    bufp->chgBit(oldp+518,(vlSelf->top__DOT__cpu__DOT__cache__DOT__cache_alloc));
    bufp->chgBit(oldp+519,(vlSelf->top__DOT__cpu__DOT__cache__DOT__cache_clean));
    bufp->chgIData(oldp+520,(vlSelf->top__DOT__cpu__DOT__cache__DOT__bo_mux__DOT__A),32);
    bufp->chgIData(oldp+521,(vlSelf->top__DOT__cpu__DOT__cache__DOT__bo_mux__DOT__B),32);
    bufp->chgIData(oldp+522,(vlSelf->top__DOT__cpu__DOT__cache__DOT__bo_mux__DOT__C),32);
    bufp->chgIData(oldp+523,(vlSelf->top__DOT__cpu__DOT__cache__DOT__bo_mux__DOT__D),32);
    bufp->chgCData(oldp+524,(vlSelf->top__DOT__cpu__DOT__cache__DOT__bo_mux__DOT__control),2);
    bufp->chgIData(oldp+525,(vlSelf->top__DOT__cpu__DOT__cache__DOT__bo_mux__DOT__result),32);
    bufp->chgBit(oldp+526,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__reset));
    bufp->chgBit(oldp+527,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__clk));
    bufp->chgBit(oldp+528,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__is_input_valid));
    bufp->chgIData(oldp+529,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__addr),32);
    bufp->chgBit(oldp+530,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__mem_read));
    bufp->chgBit(oldp+531,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__mem_write));
    bufp->chgWData(oldp+532,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__din),128);
    bufp->chgBit(oldp+536,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__is_output_valid));
    bufp->chgWData(oldp+537,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__dout),128);
    bufp->chgBit(oldp+541,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__mem_ready));
    bufp->chgIData(oldp+542,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__i),32);
    bufp->chgIData(oldp+543,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__delay_counter),32);
    bufp->chgBit(oldp+544,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__request_arrived));
    bufp->chgCData(oldp+545,(vlSelf->top__DOT__cpu__DOT__ctrl_unit__DOT__part_of_inst),7);
    bufp->chgBit(oldp+546,(vlSelf->top__DOT__cpu__DOT__ctrl_unit__DOT__is_jal));
    bufp->chgBit(oldp+547,(vlSelf->top__DOT__cpu__DOT__ctrl_unit__DOT__is_jalr));
    bufp->chgBit(oldp+548,(vlSelf->top__DOT__cpu__DOT__ctrl_unit__DOT__branch));
    bufp->chgBit(oldp+549,(vlSelf->top__DOT__cpu__DOT__ctrl_unit__DOT__mem_read));
    bufp->chgBit(oldp+550,(vlSelf->top__DOT__cpu__DOT__ctrl_unit__DOT__mem_to_reg));
    bufp->chgBit(oldp+551,(vlSelf->top__DOT__cpu__DOT__ctrl_unit__DOT__mem_write));
    bufp->chgCData(oldp+552,(vlSelf->top__DOT__cpu__DOT__ctrl_unit__DOT__alu_src_B),2);
    bufp->chgBit(oldp+553,(vlSelf->top__DOT__cpu__DOT__ctrl_unit__DOT__write_enable));
    bufp->chgBit(oldp+554,(vlSelf->top__DOT__cpu__DOT__ctrl_unit__DOT__pc_to_reg));
    bufp->chgBit(oldp+555,(vlSelf->top__DOT__cpu__DOT__ctrl_unit__DOT__is_ecall));
    bufp->chgCData(oldp+556,(vlSelf->top__DOT__cpu__DOT__ctrl_unit__DOT__opcode),7);
    bufp->chgIData(oldp+557,(vlSelf->top__DOT__cpu__DOT__forwardA_mux__DOT__A),32);
    bufp->chgIData(oldp+558,(vlSelf->top__DOT__cpu__DOT__forwardA_mux__DOT__B),32);
    bufp->chgIData(oldp+559,(vlSelf->top__DOT__cpu__DOT__forwardA_mux__DOT__C),32);
    bufp->chgIData(oldp+560,(vlSelf->top__DOT__cpu__DOT__forwardA_mux__DOT__D),32);
    bufp->chgCData(oldp+561,(vlSelf->top__DOT__cpu__DOT__forwardA_mux__DOT__control),2);
    bufp->chgIData(oldp+562,(vlSelf->top__DOT__cpu__DOT__forwardA_mux__DOT__result),32);
    bufp->chgIData(oldp+563,(vlSelf->top__DOT__cpu__DOT__forwardB_mux__DOT__A),32);
    bufp->chgIData(oldp+564,(vlSelf->top__DOT__cpu__DOT__forwardB_mux__DOT__B),32);
    bufp->chgIData(oldp+565,(vlSelf->top__DOT__cpu__DOT__forwardB_mux__DOT__C),32);
    bufp->chgIData(oldp+566,(vlSelf->top__DOT__cpu__DOT__forwardB_mux__DOT__D),32);
    bufp->chgCData(oldp+567,(vlSelf->top__DOT__cpu__DOT__forwardB_mux__DOT__control),2);
    bufp->chgIData(oldp+568,(vlSelf->top__DOT__cpu__DOT__forwardB_mux__DOT__result),32);
    bufp->chgCData(oldp+569,(vlSelf->top__DOT__cpu__DOT__forwarding_unit__DOT__ID_EX_rs1),5);
    bufp->chgCData(oldp+570,(vlSelf->top__DOT__cpu__DOT__forwarding_unit__DOT__ID_EX_rs2),5);
    bufp->chgCData(oldp+571,(vlSelf->top__DOT__cpu__DOT__forwarding_unit__DOT__EX_MEM_rd),5);
    bufp->chgCData(oldp+572,(vlSelf->top__DOT__cpu__DOT__forwarding_unit__DOT__MEM_WB_rd),5);
    bufp->chgBit(oldp+573,(vlSelf->top__DOT__cpu__DOT__forwarding_unit__DOT__EX_MEM_reg_write));
    bufp->chgBit(oldp+574,(vlSelf->top__DOT__cpu__DOT__forwarding_unit__DOT__MEM_WB_reg_write));
    bufp->chgCData(oldp+575,(vlSelf->top__DOT__cpu__DOT__forwarding_unit__DOT__forwardA),2);
    bufp->chgCData(oldp+576,(vlSelf->top__DOT__cpu__DOT__forwarding_unit__DOT__forwardB),2);
    bufp->chgCData(oldp+577,(vlSelf->top__DOT__cpu__DOT__hazard_detection_unit__DOT__IF_ID_rs1),5);
    bufp->chgCData(oldp+578,(vlSelf->top__DOT__cpu__DOT__hazard_detection_unit__DOT__IF_ID_rs2),5);
    bufp->chgBit(oldp+579,(vlSelf->top__DOT__cpu__DOT__hazard_detection_unit__DOT__ID_EX_mem_read));
    bufp->chgCData(oldp+580,(vlSelf->top__DOT__cpu__DOT__hazard_detection_unit__DOT__ID_EX_rd),5);
    bufp->chgBit(oldp+581,(vlSelf->top__DOT__cpu__DOT__hazard_detection_unit__DOT__is_ecall));
    bufp->chgBit(oldp+582,(vlSelf->top__DOT__cpu__DOT__hazard_detection_unit__DOT__ID_EX_reg_write));
    bufp->chgBit(oldp+583,(vlSelf->top__DOT__cpu__DOT__hazard_detection_unit__DOT__is_hazard));
    bufp->chgBit(oldp+584,(vlSelf->top__DOT__cpu__DOT__hazard_detection_unit__DOT__IF_ID_inst_write));
    bufp->chgBit(oldp+585,(vlSelf->top__DOT__cpu__DOT__hazard_detection_unit__DOT__PCWrite));
    bufp->chgBit(oldp+586,(vlSelf->top__DOT__cpu__DOT__imem__DOT__reset));
    bufp->chgBit(oldp+587,(vlSelf->top__DOT__cpu__DOT__imem__DOT__clk));
    bufp->chgIData(oldp+588,(vlSelf->top__DOT__cpu__DOT__imem__DOT__addr),32);
    bufp->chgIData(oldp+589,(vlSelf->top__DOT__cpu__DOT__imem__DOT__dout),32);
    bufp->chgIData(oldp+590,(vlSelf->top__DOT__cpu__DOT__imem__DOT__i),32);
    bufp->chgIData(oldp+591,(vlSelf->top__DOT__cpu__DOT__imem__DOT__imem_addr),32);
    bufp->chgIData(oldp+592,(vlSelf->top__DOT__cpu__DOT__imm_gen__DOT__part_of_inst),32);
    bufp->chgIData(oldp+593,(vlSelf->top__DOT__cpu__DOT__imm_gen__DOT__imm_gen_out),32);
    bufp->chgCData(oldp+594,(vlSelf->top__DOT__cpu__DOT__imm_gen__DOT__opcode),7);
    bufp->chgIData(oldp+595,(vlSelf->top__DOT__cpu__DOT__imm_gen__DOT__i),32);
    bufp->chgIData(oldp+596,(vlSelf->top__DOT__cpu__DOT__mem_to_reg_mux__DOT__A),32);
    bufp->chgIData(oldp+597,(vlSelf->top__DOT__cpu__DOT__mem_to_reg_mux__DOT__B),32);
    bufp->chgBit(oldp+598,(vlSelf->top__DOT__cpu__DOT__mem_to_reg_mux__DOT__Enable));
    bufp->chgIData(oldp+599,(vlSelf->top__DOT__cpu__DOT__mem_to_reg_mux__DOT__C),32);
    bufp->chgIData(oldp+600,(vlSelf->top__DOT__cpu__DOT__miss_mux__DOT__A),32);
    bufp->chgIData(oldp+601,(vlSelf->top__DOT__cpu__DOT__miss_mux__DOT__B),32);
    bufp->chgBit(oldp+602,(vlSelf->top__DOT__cpu__DOT__miss_mux__DOT__Enable));
    bufp->chgIData(oldp+603,(vlSelf->top__DOT__cpu__DOT__miss_mux__DOT__C),32);
    bufp->chgBit(oldp+604,(vlSelf->top__DOT__cpu__DOT__pc__DOT__reset));
    bufp->chgBit(oldp+605,(vlSelf->top__DOT__cpu__DOT__pc__DOT__clk));
    bufp->chgBit(oldp+606,(vlSelf->top__DOT__cpu__DOT__pc__DOT__PCWrite));
    bufp->chgIData(oldp+607,(vlSelf->top__DOT__cpu__DOT__pc__DOT__next_pc),32);
    bufp->chgIData(oldp+608,(vlSelf->top__DOT__cpu__DOT__pc__DOT__current_pc),32);
    bufp->chgBit(oldp+609,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__reset));
    bufp->chgBit(oldp+610,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__clk));
    bufp->chgCData(oldp+611,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rs1),5);
    bufp->chgCData(oldp+612,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rs2),5);
    bufp->chgCData(oldp+613,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rd),5);
    bufp->chgIData(oldp+614,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rd_din),32);
    bufp->chgBit(oldp+615,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__write_enable));
    bufp->chgIData(oldp+616,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rs1_dout),32);
    bufp->chgIData(oldp+617,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rs2_dout),32);
    bufp->chgIData(oldp+618,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[0]),32);
    bufp->chgIData(oldp+619,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[1]),32);
    bufp->chgIData(oldp+620,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[2]),32);
    bufp->chgIData(oldp+621,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[3]),32);
    bufp->chgIData(oldp+622,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[4]),32);
    bufp->chgIData(oldp+623,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[5]),32);
    bufp->chgIData(oldp+624,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[6]),32);
    bufp->chgIData(oldp+625,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[7]),32);
    bufp->chgIData(oldp+626,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[8]),32);
    bufp->chgIData(oldp+627,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[9]),32);
    bufp->chgIData(oldp+628,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[10]),32);
    bufp->chgIData(oldp+629,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[11]),32);
    bufp->chgIData(oldp+630,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[12]),32);
    bufp->chgIData(oldp+631,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[13]),32);
    bufp->chgIData(oldp+632,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[14]),32);
    bufp->chgIData(oldp+633,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[15]),32);
    bufp->chgIData(oldp+634,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[16]),32);
    bufp->chgIData(oldp+635,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[17]),32);
    bufp->chgIData(oldp+636,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[18]),32);
    bufp->chgIData(oldp+637,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[19]),32);
    bufp->chgIData(oldp+638,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[20]),32);
    bufp->chgIData(oldp+639,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[21]),32);
    bufp->chgIData(oldp+640,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[22]),32);
    bufp->chgIData(oldp+641,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[23]),32);
    bufp->chgIData(oldp+642,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[24]),32);
    bufp->chgIData(oldp+643,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[25]),32);
    bufp->chgIData(oldp+644,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[26]),32);
    bufp->chgIData(oldp+645,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[27]),32);
    bufp->chgIData(oldp+646,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[28]),32);
    bufp->chgIData(oldp+647,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[29]),32);
    bufp->chgIData(oldp+648,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[30]),32);
    bufp->chgIData(oldp+649,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[31]),32);
    bufp->chgIData(oldp+650,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__i),32);
    bufp->chgIData(oldp+651,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[0]),32);
    bufp->chgIData(oldp+652,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[1]),32);
    bufp->chgIData(oldp+653,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[2]),32);
    bufp->chgIData(oldp+654,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[3]),32);
    bufp->chgIData(oldp+655,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[4]),32);
    bufp->chgIData(oldp+656,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[5]),32);
    bufp->chgIData(oldp+657,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[6]),32);
    bufp->chgIData(oldp+658,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[7]),32);
    bufp->chgIData(oldp+659,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[8]),32);
    bufp->chgIData(oldp+660,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[9]),32);
    bufp->chgIData(oldp+661,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[10]),32);
    bufp->chgIData(oldp+662,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[11]),32);
    bufp->chgIData(oldp+663,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[12]),32);
    bufp->chgIData(oldp+664,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[13]),32);
    bufp->chgIData(oldp+665,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[14]),32);
    bufp->chgIData(oldp+666,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[15]),32);
    bufp->chgIData(oldp+667,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[16]),32);
    bufp->chgIData(oldp+668,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[17]),32);
    bufp->chgIData(oldp+669,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[18]),32);
    bufp->chgIData(oldp+670,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[19]),32);
    bufp->chgIData(oldp+671,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[20]),32);
    bufp->chgIData(oldp+672,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[21]),32);
    bufp->chgIData(oldp+673,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[22]),32);
    bufp->chgIData(oldp+674,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[23]),32);
    bufp->chgIData(oldp+675,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[24]),32);
    bufp->chgIData(oldp+676,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[25]),32);
    bufp->chgIData(oldp+677,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[26]),32);
    bufp->chgIData(oldp+678,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[27]),32);
    bufp->chgIData(oldp+679,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[28]),32);
    bufp->chgIData(oldp+680,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[29]),32);
    bufp->chgIData(oldp+681,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[30]),32);
    bufp->chgIData(oldp+682,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[31]),32);
}

void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_cleanup\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VlUnpacked<CData/*0:0*/, 1> __Vm_traceActivity;
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        __Vm_traceActivity[__Vi0] = 0;
    }
    // Body
    vlSymsp->__Vm_activity = false;
    __Vm_traceActivity[0U] = 0U;
}
